### PR TITLE
issue #659 consolidates some declarations for primary nav elements

### PR DESCRIPTION
**Pull request by xak**

### CODE REVIEW

**Comment by xak** [comment]
This it to remove the duplicated declarations for the primary nav elements

**Comment by saadmhybris** [comment]
@xak are we checking in .css files as well? Just checking as we had discussed not checking in any generated files.

**Comment by xak** [comment]
Don't we have to check in the `dist` files for them to be available for the packages? I was thinking about setting it up so that when running locally all files are compiled and served from a `.tmp` directory and only get compiled to `dist` when built for production.

**Comment by saadmhybris** [comment]
This is was the case when we didn't have automatic deployment or when we were not compiling files on the server. Now that this issue was resolved in the dev deployment bamboo plan, I don't think we need to check in compiled files anymore.

**Comment by xak** [comment]
Hmm, isn't the package pulled from Github. There's nothing in the `bower.json` or `package.json` that points to our server location, right? My https://github.com/thestrongelement/strong-css repo is packaged but isn't hosted anywhere other than Github. Maybe I'm wrong though.

**Comment by xak** [comment]
I'll merge this and we can later investigate serving locally from a different directory. This is annoying.

**Pull request merged**
