### PR TITLE
CCE-691 update visibility and add new icons

### PR DESCRIPTION
**Pull request by ghiobi**
New icons:

- commerce
- commercelg
- unpowered

Modified icons:

- visibilityoff

### CODE REVIEW

**Comment by joseegm** [comment]
@xak Who is going to review this one? Has been seating 2 days without any action.

**Comment by xak** [comment]
@joseegm Looks ok to me, but I'm not very close to 1.0 code. @saadmhybris would be better to review after his baby arrives.

**Comment by saadmhybris** [comment]
i'll pick this up. 

btw, @joseegm are we making another release to 1.5 then?

**Comment by saadmhybris** [comment]
looks good!

**Comment by joseegm** [comment]
@saadmhybris Only release an small version v1.5.7, please make a small release notes as well. That's the only change. Thank you

**Comment by saadmhybris** [comment]
ok, I'll handle all of it.

**Pull request merged**
