### PR TITLE
#1127: Docs - fix busted icons

### PR DESCRIPTION
**Pull request by saadmhybris**

### CODE REVIEW

**Comment by saadmhybris** [comment]
@joseegm  try clearing your cache. and if the page is still not right try - `bundle exec jekyll build` from `docs` folder to rebuild the site.

**Comment by joseegm** [comment]
@saadmhybris 
Rebuilding the website worked.

**Comment by saadmhybris** [comment]
@joseegm pls merge if this looks good. this will not hold up the release though.

**Comment by saadmhybris** [comment]
@joseegm pls merge if this looks good. this will not hold up the release though.

**Comment by joseegm** [comment]
Done

**Pull request merged**
