### PR TITLE
#1168 updates starter pages with new layout containers

### PR DESCRIPTION
**Pull request by xak**
#1168 

Updates all three starter pages (card, tree, and table) to use new layout containers. Also, includes a few small tweaks of various margins.

### CODE REVIEW

**Comment by xak** [comment]
@saadmhybris and @LeoT7508 Can you guys take a look at these? 

See branch `feature/1168`. Updated the three starter pages ...
http://localhost:3030/pages/table
http://localhost:3030/pages/tree
http://localhost:3030/pages/cards

These now use the ui, app, page, and section layout containers.

**Comment by saadmhybris** [comment]
can be merged once @LeoT7508 is done reviewing.

**Comment by LeoT7508** [comment]
@xak 

Table:
- Include the new 40px before 20px after a section. Looks like right now its 52px before. 
- The panel controls should have 16px below. 
- There should be a 1 px rule about the column headers. 

Tree:
- Include the new 40px before 20px after a section. Looks like right now its 52px before. 
- The panel controls should have 16px below. 

Cards:
- Include the new 40px before 20px after a section. Looks like right now its 52px before. 
- The panel controls should have 16px below. 

@saadmhybris 

We need to fix the icons, they were right for a while, now they aren't correct.

**Comment by xak** [comment]
@LeoT7508 Fixed.

**Comment by LeoT7508** [comment]
@xak @saadmhybris 

This checks out from the visual side. 

Thanks.

**Pull request merged**
