### PR TITLE
#916 contextual menu

### PR DESCRIPTION
**Pull request by xak**
#916

### CODE REVIEW

**Comment by xak** [comment]
Ready for review ... branch `feature/916` at http://localhost:3030/contextual-menu

## NOTE: This is not a standalone component. You can use any type of button and a dropdown menu.

**Comment by saadmhybris** [comment]
looks good. @LeoT7508 let me know when you are done reviewing and I'll merge this.

**Comment by LeoT7508** [comment]
@saadmhybris 

This isn't correct. The icon is wrong. It should be vertical. And we don't have a "..." with "more" below it. Also when I click on the icon the menu opens but won't close. It just stays open. It should close when I click away from it.

**Comment by xak** [comment]
@LeoT7508 I'm using the "more" icon we have now. http://sap.github.io/techne/icons.html. And the last example is the option you have for the Action Bar. You comped a "more" option there so I'm demoing that option.

**Comment by LeoT7508** [comment]
@xak @saadmhybris 

Pending icon updates by me this is good to go.

**Comment by saadmhybris** [comment]
@LeoT7508 we went back and forth on the more icon being verticle or horizontal in the past. we settled on horizontal because it allowed better visibility and hit area on mobile. You can check out the contextual menu page on 1.5 and it's horizontal - https://techne.yaas.io/components/Contextual-Menu.html

**Comment by LeoT7508** [comment]
@saadmhybris 

We're going with vertical.

**Comment by xak** [comment]
Is this OK?

**Comment by LeoT7508** [comment]
@xak 

Yup. We should be good. I talked to Jeanne and Manu about this before when we decided to change it.

**Comment by saadmhybris** [comment]
Sounds good on the vertical icon

**Pull request merged**
