### PR TITLE
Feature/725

### PR DESCRIPTION
**Pull request by saadmhybris**

### CODE REVIEW

**Comment by saadmhybris** [comment]
I have added a layout-test page that can be removed later. Just wanted to see how all my styles would stack up as the cards page does not use all the headings.

**Comment by saadmhybris** [comment]
@xak removed kss files. sorry about that.

**Comment by xak** [comment]
@saadmhybris What about the `src/less/globals/_resource-paths.less` file? Do you need that?

**Comment by saadmhybris** [comment]
@xak  removed less folder and also resolved merge conflicts.

**Comment by xak** [comment]
@saadmhybris Still have a conflict. Not sure why that card CSS file made it in anyway.

**Comment by saadmhybris** [comment]
@xak removed techne-cards.css

sorry i have to start fresh as things got messy with v1.5 and 2.0 stuff

**Pull request merged**
