### PR TITLE
Feature/717 secondary nav

### PR DESCRIPTION
**Pull request by like-me1**
only common styling for left side nav was created according to available styling under https://github.com/SAP/techne/issues/718. Now it's visible on Components page only and once the rest of the pages will have its own left side structure the styling will be automatically applied. Everything related to JS or behavior needs to be addressed in another task as it was planned in #718

### CODE REVIEW

**Comment by saadmhybris** [comment]
@like-me1 I pulled down the branch and the site did not build correctly. i get a 404 on techne-styleguide.css. 

Also, the branch has conflicts now since there were some PRs merged earlier.

**Comment by like-me1** [comment]
@saadmhybris I'll fix visual issues and resolve conflicts from v2.0 branch. But functionality - wise it's a different ticket please. There was one #718 but it was closed don't know why. In this ticket was only mentioned to style the left side nav according to https://devportal.yaas.io/tools/. And I created a future place for the nav which doesn't exist for the rest pages but will, once the pages and nav will in place.

**Comment by saadmhybris** [comment]
@like-me1 can you please verify the conflicts again. I see still see the message that this branch has conflicts.

**Comment by like-me1** [comment]
@saadmhybris sure, working on it

**Comment by like-me1** [comment]
@saadmhybris ready to go for the review. The mobile version for pages' left side nav is hidden for now. It needs some brainstorming on how to implement it ina best way.

**Comment by saadmhybris** [comment]
The PR looks good. There is an issue with mobile nav links in the component page, but I will create a separate issue for that.

**Pull request merged**
