### PR TITLE
#681: Global Build and Clean gulp commands added. Docs clean refactor…

### PR DESCRIPTION
**Pull request by joseegm**
…ed to use the data on the config file

### CODE REVIEW

**Comment by xak** [comment]
These are not needed at this time. Deployment and publishing tasks where both outputs will be built and coordinated have yet to be written. I prefer to maintain a separation between the site and the package until we have an explicit need to do otherwise.

Running `gulp docs-build` builds the package first and accomplishes the same thing. 

However, this should be revisited since there are times when we deploy the site independently of a package version bump, and coupling the two risks introducing unintended library changes. Of course, it's not hard to manage this manually for hot fixes, but we should look at this as part of the deployment implementation if we want to build in concrete separation. For example, we could rely on bower to pull the latest version of Techne when production builds are executed by Bamboo. See #647

**Comment by joseegm** [comment]
@xak Think I didn't explained the rationale of this PR, some more explanation is needed.

Since we are using unconventional gulp tasks commands, see other libraries for reference:
https://github.com/angular/material2/blob/master/tools/gulp/tasks/publish.ts#L104

Convention in the angular world -our main users front-end framework- is `gulp <action>:<environment>`, with common action names like `gulp build` to build the whole solution, `gulp build:dist` for production.

Our current implementation uses `gulp <module>-<action> --<environment>` that's why we need a conventional way to build the whole package with easy, using the short commands `gulp build` and `gulp build --production` instead of `gulp docs-build` which is something different we have to remember and doesn't reflect if it builds the whole solution, only the docs.

Now you have more elements.

**Comment by xak** [comment]
@joseegm This merge has been reverted. It was not your call to merge this. I indicated that this was not needed at this time therefore it was not merged. There are three developers working the project framework and when this is needed it will be added at that time. At this time, it only adds clutter to the project.

If you have a tech-related issue, please create the issue and leave it in the backlog. It will be prioritized along with every other issue. You do not need to do the task yourself or add it to the implementation board with your own priority.

Thanks.

**Comment by joseegm** [comment]
@xak 

The comment https://github.com/SAP/techne/pull/682#issuecomment-302008386 was sitting without answer for a very long while. 

As per info on that comment major editors and IDEs pick **conventional** gulp tasks out of the box, they usually named `build`. See:
* https://github.com/AtomBuild/atom-build-gulp/blob/master/spec/build-gulp-spec.js#L65
* https://code.visualstudio.com/docs/editor/tasks
* https://blogs.msdn.microsoft.com/webdev/2016/01/06/task-runners-in-visual-studio-2015/

Which makes building the library or website with a short-cut a breeze. Not like right now that we don't have **conventional named** gulp tasks.

The use case is valid and meaningful, fully documented on #681, the code was valid, no conflict on the PR... 

Do you suggest drop that and open a ticket to to the same thing? 
To develop again the same thing?

Let me know if you need me to open a Technical ticket for this, so it gets developed again.

**Comment by xak** [comment]
@joseegm The examples you include do not assume any conventional task names. They either pick up the tasks as defined in the gulpfile or require a separate tasks definition file. I'm not debating that many projects use `build`, as I've said before, we may need this in the future but it is not an MVP need now.

With this and any tech-related issue or concerns, you should open an issue and explain why you are requesting the change. That's all you have to do. If the issue is important then let me know and we can discuss the priority, otherwise the issue will be assessed and prioritized along with everything else. For this, you created the issue, added it to the implementation board, coded it, moved the ticket to done, and created a PR — all within a few hours. That is a hotfix process, not a feature process. 

If you want to have a closer look at the tasks in use and recommend a new approach that is more in line with other projects, then open a new issue and outline your approach. We'll take a look and validate it against all of our needs.

**Comment by joseegm** [comment]
@xak All right, then I'll open an issue and request the same change it is already developed. Good.

**Pull request merged**
