### PR TITLE
Feature/785

### PR DESCRIPTION
**Pull request by xak**
This adds a lot to the layout pillar of the library. See /layout.html for examples of the UI and columns.

# $tn-breakpoints

Adds breakpoint map.
```
    xs: 320px,
    s: 768px,
    m: 1024px,
    l: 1440px,
    xl: 1580px,
```

# @mixin tn-at-media()

The mixin picks up the breakpoints. Assumes mobile-first, i.e., it only goes up.
```
@include tn-at-media(m) {
  //rules for 1024 and up
}
```

# .tn-ui

Sets high-level page layout structure for starter pages. There are too many unknowns to take this much further but it's a good initial draft.

```
.tn-ui
  .tn-ui__header
  .tn-ui__app
  .tn-ui__sidebar
  .tn-ui__main
```

# .tn-container

Basic parent container for columns with several flavors.
```
.tn-container (has a max-width with left and right padding)
.tn-container--fluid (has no max-width but retains left and right padding)
.tn-container--bleed (has max-width but with no left and right padding)
.tn-container--centered (auto left and right margins)
```

# .tn-col-*

Based on a 12-colum grid, with `.tn-col-1` through `.tn-col-12` available. Responsive behavior is built-in, containers stack below `s` breakpoint.

#  @function tn-if() 

Convenience function to test booleans flags, e.g., fixed global header flag can be toggled but a fixed means the content must shift. 
```
    &__header {
        position: tn-if($tn-ui-header-fixed, fixed static);
    }
    &__app {
        margin-top: tn-if($tn-ui-header-fixed, $tn-ui-header-height 0);
        height: tn-if($tn-ui-header-fixed, calc(100vh - #{$tn-ui-header-height}) 100vh);
    }
```

### CODE REVIEW

**Comment by xak** [comment]
#785

**Comment by joseegm** [comment]
@xak 
Did you looked at the inflexion points defined at #739.

The sizes on https://github.com/SAP/techne/pull/843#issue-245787203 are not the same as the one defined on #739

**Comment by xak** [comment]
@joseegm No, I didn't. #739 was closed but not documented anyway. How did you devise those sizes?

Let's defer any changes right now until layouts become more defined. That's where they will be most useful and we have no good responsive examples yet. The breakpoints are easy enough to change.

**Comment by joseegm** [comment]
@xak 
The sizes are a simplified version from the ones on bootstrap.

The sizes were used to define the Website components inflexion points at https://github.com/SAP/techne/issues/740, **that's a issue that you participated**.

We can move on, but please pay attention to already defined material in the future. 

The responsive inflexion points will be tested in QA as well.

**Comment by xak** [comment]
@joseegm Please cut me some slack about "pay[ing] attention to already defined material" when I have to search closed issues to find "decisions." 

And if I can be specific, I've never heard the term ["inflection point"](https://www.bing.com/search?q=css+inflection+point&go=Search&qs=n&form=QBRE&sp=-1&pq=undefined&sc=0-19&sk=&cvid=6C08AD95B8FB4B99BA9650D52F15C3BC) before working here, the term ["breakpoint"](https://www.bing.com/search?q=css+breakpoints&go=Search&qs=n&form=QBRE&sp=-1&pq=css+breakpoints&sc=8-15&sk=&cvid=58D73F8CDC2948DF87C3DCC55E15FF14) is much more common. But even so, [search "inflection"](https://github.com/SAP/techne/issues?utf8=✓&q=is%3Aissue%20inflection) through our issues and you'll see the problem. This was done awhile back so I'll cut you some slack for why it may not be on the Wiki and I'll forgive your misspelling. Now I know where to find it, they can be adjusted, no big deal.

It's clear you don't like anything I do but I'm trying to get stuff done. #846 has been opened to adjust the breakpoints.

**Comment by joseegm** [comment]
You have a point on the "inflexion" term. That was the name we were using in the past here, didn't thought much about it. Is changed now on all relevant places, if you see any other place where the is please let me know to change it.

Thanks for open #846

**Pull request merged**
