### PR TITLE
Feature/cce 569

### PR DESCRIPTION
**Pull request by jakub-gawlas**
Added two new icons, feedback and gethelp, which are used in new component feedback-menu. To styling these icons in feedback-menu I created new component button-icon (but not sure if it should be component).
I will be very grateful for review ;)
Thanks!

### CODE REVIEW

**Comment by saadmhybris** [comment]
@jakub-gawlas - I am seeing couple of issues this with this. Please see the tickets for screen shots - 

https://jira.hybris.com/browse/CCE-569

**Comment by jakub-gawlas** [comment]
fixes done ;)

**Comment by saadmhybris** [comment]
@jakub-gawlas  - here are conflicts on the branch now. please resolve those and we should be good to merge.

**Comment by joseegm** [comment]
Can we leave out the "Button Icon" component out of the guidelines for this release?

It is not quite fitting the visual style. 
The definition and CSS can stay. Probably @jakub-gawlas need it now. 

The component needs some more design work.

@jakub-gawlas Agreed? Just remove the reference on the _patterns template.

**Comment by derberg** [comment]
We need it, otherwise we are going to be delayed with implementation of new feedback forms. This is basically why we did a pull request instead of logging an issue. Designs are from Dieter and Jeanne.

Regarding CLA. He won't be able to sign it I think as he made a mistake of comiting with a different email address. That shouldn't be a problem though as CLA is for external contributors, while he is an SAP employee.

**Comment by joseegm** [comment]
@derberg Thanks for the clarification.

Made some changes to the documentation text.

The branch have still conflicting files... Once these has been resolved, we are good to go with the release, as planned, for tomorrow late afternoon.

I don't know if we can merge it without the CLA been signed, but we'll see soon enough ;)

**Comment by jakub-gawlas** [comment]
@joseegm @saadmhybris conflicts resolved, CLA signed, ready to merge :)

**Pull request merged**
