### PR TITLE
CCE-449 : add hybris experts link to homepage

### PR DESCRIPTION
**Pull request by saadmhybris**

### CODE REVIEW

**Comment by HybrisRawls** [comment]
@saadmhybris merge develop into this branch

**Comment by saadmhybris** [comment]
@HybrisRawls merged.

**Comment by HybrisRawls** [comment]
@saadmhybris please merge develop back into this branch.  The changes that have the updated spelling on Techné don't seem to be in

**Comment by saadmhybris** [comment]
@HybrisRawls for some reason merging develop in this branch was not overwriting the the homepage file so I updated it manually. I also found some other instances on other pages that I updated.

**Pull request merged**
