### PR TITLE
Feature/955

### PR DESCRIPTION
**Pull request by xak**
#955

### CODE REVIEW

**Comment by xak** [comment]
@saadmhybris I made some modifications to the starter page ...

- Fix the icons (it was a simple routing fix in `app.js`
- Updated the cards to match the content at https://techne.yaas.io/starterpages/cards.html
- Updated card to use the `label` component
- Changed the `action-bar` background to match the toolbar (the correct one) and added borders (per the design)
- Added bottom margin to the `toolbar`
- Added the "description help" text and created some helpers to enable the layout (temp solution)

@LeoT7508 Please take a look in branch `feature/955` at localhost:3030/pages/cards. There are some things missing and not quite right that we should follow up on. Please open an issue with anything you see that needs to be fixed, like the "Add" button still needs to be done, the cards are padded too much and squish awkwardly, etc.

I think we're OK to release as long as we capture what is out of sync and circle back.

**Comment by saadmhybris** [comment]
looks good, thanks!

**Comment by LeoT7508** [comment]
@xak 

Looks like you deleted branch 955. Please let me know when its back up so I can check it out, thanks.

**Comment by xak** [comment]
@LeoT7508 Sorry, @saadmhybris merged it so you can see it in branch `v2.0` now.

**Pull request merged**
